import { notFound } from "next/navigation";
import { getPostBySlug } from "@/lib/content";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default async function TypstPage({
  params,
}: {
  params: Promise<{ section: string; slug: string[] }>;
}) {
  const { section, slug } = await params;
  
  if (!["notes", "tutorial", "misc"].includes(section)) {
    notFound();
  }

  const post = getPostBySlug(section, slug);

  if (!post) {
    notFound();
  }

  return (
    <div className="max-w-6xl mx-auto px-4 md:px-6 py-12">
      <div className="mb-8">
        <Link 
          href={`/${section}`} 
          className="inline-flex items-center px-4 py-2 bg-black/5 dark:bg-white/5 hover:bg-black/10 dark:hover:bg-white/10 text-zinc-600 dark:text-zinc-300 rounded-lg transition-colors font-medium text-sm"
        >
          <ArrowLeft className="w-4 h-4 mr-2" /> Back to Notebook
        </Link>
      </div>
      
      {/* Book-like container */}
      <div className="bg-[#fdfdfc] dark:bg-[#1a1a1c] p-0 md:p-8 rounded-xl shadow-2xl border border-black/5 dark:border-white/5 overflow-hidden">
        {/* We use dangerouslySetInnerHTML to inject the pure SVG generated by Typst */}
        <div 
          className="typst-render-container w-full flex justify-center"
          dangerouslySetInnerHTML={{ __html: post.content }} 
        />
      </div>
    </div>
  );
}
